### PR TITLE
Virtual to phyiscal dict added to measurements

### PR DESCRIPTION
**Pull request by SalonikResch5**
From our perspective, the Measurements object having a "virtual to physical" dictionary for qubit mapping is the easiest solution. We are not sure about issues from the software side.

Having some method of virtual to physical mapping available will be essential for our mitigation strategies to work.

### CODE REVIEW

**Comment by AthenaCaesura** [comment]
Are you referring to the readout error correction? Because we already have a dictionary implemented in `orquestra-qiskit` to do just that. Or are there other use cases?

**Comment by AthenaCaesura** [comment]
Still, I don't think that it is strictly necessary to add an extra property to measurements just for this dictionary. Can't you just define this dictionary in your workflow? If you need to associate a different mapping with each measurement, maybe defining a `NamedTuple` would be better?

To me, it's not intuitive to have a mapping from virtual to physical qubits associated with every measurement regardless of the backend, as not every backend exposes virtual qubits in the way qiskit does.

**Comment by SalonikResch5** [comment]
Ok. I think then only my changes to orquestra-qiskit will be necessary.

**Comment by AthenaCaesura** [comment]
Looking forward to the qiskit PR! Let me know if there are any issues with it. 🙂

**Comment by akataba** [comment]
> 

@AthenaCaesura I don't understand your solution. The PR request in orquestra qiskit will calculate the virtual to physical qubit mappings so how should it be returned to the user? The user at this point gets back measurement objects with bit string outcomes but often times this is not as useful as you might think because we don't know the outcome of the transpilation process i.e what qubits were actually measured. I think intuitively it makes sense for measurement bit string to come with the label for which qubits were measured to produce that bit string. I think this is a necessary requirement especially when most times we will not have access to the compiler/transpiler but might still want to preserve information about what qubits were measured.

**Comment by AthenaCaesura** [comment]
To be clear, I didn't really propose a solution here. I was just trying to say that it makes little sense to add a virtual to physical qubits mapping to the `measurement` object with the current form of our circuits. Right now, our circuits operate under the assumption that all qubits are measured at the end of your circuit. You can then use the `subdistribution` function of `MeasurementOutcomeDistirbution` to trace out qubits you want to ignore.

The solution to your problem that I had in mind was to add `virtual_to_physical_qubits_dicts` as a property of the `QiskitBackend` object. One could then add all the dictionaries associated with a given call of `aggregate_measurements` as you compute them.

**Comment by AthenaCaesura** [comment]
Closing as we solved the problem for `orquestra-qiskit`.

**Pull request closed without merging**
